-- ============================================================
-- PET HOTEL MANAGEMENT SYSTEM - Oracle Database Schema
-- DDL Script: Tạo bảng (Chuẩn hóa 3NF)
-- ============================================================

-- ============================================================
-- GHI CHÚ VỀ CHUẨN HÓA (Normalization - 3NF):
-- 
-- 1NF: Mỗi cột chứa giá trị nguyên tử, không có nhóm lặp.
-- 2NF: Tất cả cột không khóa phụ thuộc hoàn toàn vào khóa chính.
-- 3NF: Không có phụ thuộc bắc cầu (transitive dependency).
--
-- Ví dụ: Bảng KHACH_HANG và THU_CUNG được tách riêng
-- thay vì gộp chung để tránh dư thừa dữ liệu (Anomalies):
--   - Insert Anomaly: Không thể thêm thú cưng nếu chưa có khách.
--   - Update Anomaly: Cập nhật SĐT khách phải sửa nhiều dòng.
--   - Delete Anomaly: Xóa thú cưng có thể mất thông tin khách.
-- ============================================================

-- Xóa bảng nếu đã tồn tại (theo thứ tự phụ thuộc)
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'CAP_NHAT_THU_CUNG', 'CHI_TIET_DICH_VU', 'HOA_DON', 'DAT_PHONG', 
        'THU_CUNG', 'TAI_KHOAN', 'PHONG', 'LOAI_PHONG', 'DICH_VU', 
        'KHACH_HANG', 'NHAN_VIEN'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Xóa sequence nếu đã tồn tại
BEGIN
    FOR s IN (SELECT sequence_name FROM user_sequences WHERE sequence_name IN (
        'SEQ_KHACH_HANG', 'SEQ_THU_CUNG', 'SEQ_LOAI_PHONG', 'SEQ_PHONG',
        'SEQ_DICH_VU', 'SEQ_NHAN_VIEN', 'SEQ_DAT_PHONG', 'SEQ_HOA_DON',
        'SEQ_CHI_TIET_DV', 'SEQ_TAI_KHOAN', 'SEQ_CAP_NHAT_TC'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
    END LOOP;
END;
/

-- ============================================================
-- SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_KHACH_HANG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_THU_CUNG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_LOAI_PHONG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PHONG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DICH_VU START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_NHAN_VIEN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DAT_PHONG START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HOA_DON START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CHI_TIET_DV START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TAI_KHOAN START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CAP_NHAT_TC START WITH 1 INCREMENT BY 1 NOCACHE;

-- ============================================================
-- 1. BẢNG NHÂN VIÊN (NHAN_VIEN)
-- ============================================================
CREATE TABLE NHAN_VIEN (
    MA_NV           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HO_TEN          VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100)   CONSTRAINT UQ_NV_EMAIL UNIQUE,
    SO_DIEN_THOAI   VARCHAR2(15)    NOT NULL,
    CHUC_VU         VARCHAR2(50)    NOT NULL,
    NGAY_VAO_LAM    DATE            DEFAULT SYSDATE NOT NULL,
    TRANG_THAI      VARCHAR2(20)    DEFAULT 'DANG_LAM' 
                    CONSTRAINT CK_NV_TRANG_THAI 
                    CHECK (TRANG_THAI IN ('DANG_LAM', 'NGHI_VIEC', 'TAM_NGHI')),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================================
-- 2. BẢNG KHÁCH HÀNG (KHACH_HANG)
-- ============================================================
CREATE TABLE KHACH_HANG (
    MA_KH           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HO_TEN          VARCHAR2(100)   NOT NULL,
    EMAIL           VARCHAR2(100)   CONSTRAINT UQ_KH_EMAIL UNIQUE,
    SO_DIEN_THOAI   VARCHAR2(15)    NOT NULL CONSTRAINT UQ_KH_SDT UNIQUE,
    DIA_CHI         VARCHAR2(255),
    NGAY_DANG_KY    DATE            DEFAULT SYSDATE NOT NULL,
    GHI_CHU         VARCHAR2(500),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================================
-- 3. BẢNG THÚ CƯNG (THU_CUNG)
-- Quan hệ: N-1 với KHACH_HANG (1 khách có thể có nhiều thú cưng)
-- ============================================================
CREATE TABLE THU_CUNG (
    MA_TC           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_KH           NUMBER          NOT NULL,
    TEN_TC          VARCHAR2(100)   NOT NULL,
    LOAI            VARCHAR2(50)    NOT NULL
                    CONSTRAINT CK_TC_LOAI 
                    CHECK (LOAI IN ('CHO', 'MEO', 'CHIM', 'CA', 'HAMSTER', 'THO', 'KHAC')),
    GIONG           VARCHAR2(100),
    TUOI            NUMBER(3)       CONSTRAINT CK_TC_TUOI CHECK (TUOI >= 0 AND TUOI <= 100),
    CAN_NANG        NUMBER(5,2)     CONSTRAINT CK_TC_CAN_NANG CHECK (CAN_NANG > 0),
    GIOI_TINH       VARCHAR2(10)    
                    CONSTRAINT CK_TC_GIOI_TINH CHECK (GIOI_TINH IN ('DUC', 'CAI')),
    TINH_TRANG_SK   VARCHAR2(255),
    GHI_CHU         VARCHAR2(500),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_TC_KH FOREIGN KEY (MA_KH) 
        REFERENCES KHACH_HANG(MA_KH) ON DELETE CASCADE
);

-- ============================================================
-- 4. BẢNG LOẠI PHÒNG (LOAI_PHONG)
-- Tách riêng để đạt 3NF: tránh lặp thông tin loại phòng
-- ============================================================
CREATE TABLE LOAI_PHONG (
    MA_LOAI_PHONG   NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEN_LOAI        VARCHAR2(100)   NOT NULL CONSTRAINT UQ_LP_TEN UNIQUE,
    MO_TA           VARCHAR2(500),
    GIA_MOI_NGAY    NUMBER(12,2)    NOT NULL CONSTRAINT CK_LP_GIA CHECK (GIA_MOI_NGAY > 0),
    LOAI_THU_CUNG   VARCHAR2(50)    NOT NULL
                    CONSTRAINT CK_LP_LOAI_TC 
                    CHECK (LOAI_THU_CUNG IN ('CHO', 'MEO', 'CHIM', 'CA', 'HAMSTER', 'THO', 'KHAC', 'TAT_CA')),
    SUC_CHUA        NUMBER(3)       DEFAULT 1 NOT NULL CONSTRAINT CK_LP_SUC_CHUA CHECK (SUC_CHUA > 0)
);

-- ============================================================
-- 5. BẢNG PHÒNG (PHONG)
-- Quan hệ: N-1 với LOAI_PHONG
-- ============================================================
CREATE TABLE PHONG (
    MA_PHONG        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_LOAI_PHONG   NUMBER          NOT NULL,
    TEN_PHONG       VARCHAR2(50)    NOT NULL CONSTRAINT UQ_P_TEN UNIQUE,
    TANG            NUMBER(2)       DEFAULT 1 NOT NULL,
    TRANG_THAI      VARCHAR2(20)    DEFAULT 'TRONG'
                    CONSTRAINT CK_P_TRANG_THAI 
                    CHECK (TRANG_THAI IN ('TRONG', 'DA_DAT', 'DANG_SU_DUNG', 'BAO_TRI')),
    GHI_CHU         VARCHAR2(500),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_P_LP FOREIGN KEY (MA_LOAI_PHONG) 
        REFERENCES LOAI_PHONG(MA_LOAI_PHONG)
);

-- ============================================================
-- 6. BẢNG DỊCH VỤ (DICH_VU)
-- ============================================================
CREATE TABLE DICH_VU (
    MA_DV           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TEN_DV          VARCHAR2(100)   NOT NULL CONSTRAINT UQ_DV_TEN UNIQUE,
    MO_TA           VARCHAR2(500),
    GIA             NUMBER(12,2)    NOT NULL CONSTRAINT CK_DV_GIA CHECK (GIA >= 0),
    DON_VI          VARCHAR2(30)    DEFAULT 'LAN' 
                    CONSTRAINT CK_DV_DON_VI CHECK (DON_VI IN ('LAN', 'GIO', 'NGAY', 'LIEU_TRINH')),
    TRANG_THAI      VARCHAR2(20)    DEFAULT 'HOAT_DONG'
                    CONSTRAINT CK_DV_TRANG_THAI 
                    CHECK (TRANG_THAI IN ('HOAT_DONG', 'NGUNG')),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL
);

-- ============================================================
-- 7. BẢNG ĐẶT PHÒNG (DAT_PHONG)
-- Quan hệ: N-1 với THU_CUNG, PHONG, NHAN_VIEN
-- ============================================================
CREATE TABLE DAT_PHONG (
    MA_DAT_PHONG    NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_TC           NUMBER          NOT NULL,
    MA_PHONG        NUMBER          NOT NULL,
    MA_NV           NUMBER,
    NGAY_NHAN       DATE            NOT NULL,
    NGAY_TRA        DATE            NOT NULL,
    TRANG_THAI      VARCHAR2(20)    DEFAULT 'DA_DAT'
                    CONSTRAINT CK_DP_TRANG_THAI 
                    CHECK (TRANG_THAI IN ('DA_DAT', 'NHAN_PHONG', 'TRA_PHONG', 'HUY')),
    GHI_CHU         VARCHAR2(500),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_DP_TC FOREIGN KEY (MA_TC) 
        REFERENCES THU_CUNG(MA_TC),
    CONSTRAINT FK_DP_PHONG FOREIGN KEY (MA_PHONG) 
        REFERENCES PHONG(MA_PHONG),
    CONSTRAINT FK_DP_NV FOREIGN KEY (MA_NV) 
        REFERENCES NHAN_VIEN(MA_NV),
    CONSTRAINT CK_DP_NGAY CHECK (NGAY_TRA > NGAY_NHAN)
);

-- ============================================================
-- 8. BẢNG HÓA ĐƠN (HOA_DON)
-- Quan hệ: 1-1 với DAT_PHONG
-- ============================================================
CREATE TABLE HOA_DON (
    MA_HD           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_DAT_PHONG    NUMBER          NOT NULL CONSTRAINT UQ_HD_DP UNIQUE,
    TIEN_PHONG      NUMBER(12,2)    DEFAULT 0 NOT NULL,
    TIEN_DICH_VU    NUMBER(12,2)    DEFAULT 0 NOT NULL,
    GIAM_GIA        NUMBER(5,2)     DEFAULT 0 
                    CONSTRAINT CK_HD_GIAM_GIA CHECK (GIAM_GIA >= 0 AND GIAM_GIA <= 100),
    TONG_TIEN       NUMBER(14,2)    DEFAULT 0 NOT NULL,
    TRANG_THAI      VARCHAR2(20)    DEFAULT 'CHUA_THANH_TOAN'
                    CONSTRAINT CK_HD_TRANG_THAI 
                    CHECK (TRANG_THAI IN ('CHUA_THANH_TOAN', 'DA_THANH_TOAN', 'HUY')),
    NGAY_THANH_TOAN DATE,
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_HD_DP FOREIGN KEY (MA_DAT_PHONG) 
        REFERENCES DAT_PHONG(MA_DAT_PHONG)
);

-- ============================================================
-- 9. BẢNG CHI TIẾT DỊCH VỤ (CHI_TIET_DICH_VU)
-- Bảng trung gian: Quan hệ N-N giữa DAT_PHONG và DICH_VU
-- ============================================================
CREATE TABLE CHI_TIET_DICH_VU (
    MA_CT_DV        NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_DAT_PHONG    NUMBER          NOT NULL,
    MA_DV           NUMBER          NOT NULL,
    SO_LUONG        NUMBER(5)       DEFAULT 1 NOT NULL CONSTRAINT CK_CTDV_SL CHECK (SO_LUONG > 0),
    DON_GIA         NUMBER(12,2)    NOT NULL CONSTRAINT CK_CTDV_DG CHECK (DON_GIA >= 0),
    THANH_TIEN      NUMBER(14,2)    NOT NULL,
    NGAY_SU_DUNG    DATE            DEFAULT SYSDATE NOT NULL,
    GHI_CHU         VARCHAR2(500),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_CTDV_DP FOREIGN KEY (MA_DAT_PHONG) 
        REFERENCES DAT_PHONG(MA_DAT_PHONG),
    CONSTRAINT FK_CTDV_DV FOREIGN KEY (MA_DV) 
        REFERENCES DICH_VU(MA_DV)
);

-- ============================================================
-- 10. BẢNG TÀI KHOẢN KHÁCH HÀNG (TAI_KHOAN)
-- Quan hệ: 1-1 với KHACH_HANG (mỗi khách hàng có 1 tài khoản)
-- ============================================================
CREATE TABLE TAI_KHOAN (
    MA_TK           NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_KH           NUMBER          NOT NULL CONSTRAINT UQ_TK_KH UNIQUE,
    EMAIL           VARCHAR2(100)   NOT NULL CONSTRAINT UQ_TK_EMAIL UNIQUE,
    MAT_KHAU        VARCHAR2(255)   NOT NULL,
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_TK_KH FOREIGN KEY (MA_KH)
        REFERENCES KHACH_HANG(MA_KH) ON DELETE CASCADE
);

-- ============================================================
-- 11. BẢNG CẬP NHẬT THÚ CƯNG HÀNG NGÀY (CAP_NHAT_THU_CUNG)
-- Quan hệ: N-1 với DAT_PHONG, THU_CUNG, NHAN_VIEN
-- Nhân viên cập nhật tình trạng và ảnh thú cưng mỗi ngày
-- ============================================================
CREATE TABLE CAP_NHAT_THU_CUNG (
    MA_CAP_NHAT     NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MA_DAT_PHONG    NUMBER          NOT NULL,
    MA_TC           NUMBER          NOT NULL,
    MA_NV           NUMBER          NOT NULL,
    NGAY            DATE            DEFAULT SYSDATE NOT NULL,
    TINH_TRANG      VARCHAR2(50)    NOT NULL
                    CONSTRAINT CK_CNTC_TINH_TRANG
                    CHECK (TINH_TRANG IN ('Tot', 'Binh thuong', 'Can theo doi', 'Benh')),
    GHI_CHU         VARCHAR2(1000),
    HOAT_DONG       VARCHAR2(500),
    HINH_ANH        VARCHAR2(2000),
    NGAY_TAO        TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT FK_CNTC_DP FOREIGN KEY (MA_DAT_PHONG)
        REFERENCES DAT_PHONG(MA_DAT_PHONG),
    CONSTRAINT FK_CNTC_TC FOREIGN KEY (MA_TC)
        REFERENCES THU_CUNG(MA_TC),
    CONSTRAINT FK_CNTC_NV FOREIGN KEY (MA_NV)
        REFERENCES NHAN_VIEN(MA_NV)
);

-- ============================================================
-- INDEXES (Tối ưu truy vấn)
-- ============================================================
CREATE INDEX IDX_TC_MA_KH ON THU_CUNG(MA_KH);
CREATE INDEX IDX_PHONG_LOAI ON PHONG(MA_LOAI_PHONG);
CREATE INDEX IDX_PHONG_TRANG_THAI ON PHONG(TRANG_THAI);
CREATE INDEX IDX_DP_MA_TC ON DAT_PHONG(MA_TC);
CREATE INDEX IDX_DP_MA_PHONG ON DAT_PHONG(MA_PHONG);
CREATE INDEX IDX_DP_NGAY ON DAT_PHONG(NGAY_NHAN, NGAY_TRA);
CREATE INDEX IDX_DP_TRANG_THAI ON DAT_PHONG(TRANG_THAI);
CREATE INDEX IDX_HD_TRANG_THAI ON HOA_DON(TRANG_THAI);
CREATE INDEX IDX_CTDV_DP ON CHI_TIET_DICH_VU(MA_DAT_PHONG);
CREATE INDEX IDX_TK_MA_KH ON TAI_KHOAN(MA_KH);
CREATE INDEX IDX_TK_EMAIL ON TAI_KHOAN(EMAIL);
CREATE INDEX IDX_CNTC_DP ON CAP_NHAT_THU_CUNG(MA_DAT_PHONG);
CREATE INDEX IDX_CNTC_TC ON CAP_NHAT_THU_CUNG(MA_TC);
CREATE INDEX IDX_CNTC_NGAY ON CAP_NHAT_THU_CUNG(NGAY);

COMMIT;
